site:
  title: Docs Site
  start_page: field-day::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: https://github.com/Field-Day-2022/field-day-antora-ui/releases/latest/download/ui-bundle.zip