site:
  title: Field Day Docs
  start_page: field-day::index.adoc

content:
  sources:
    - url: .
      branches: HEAD

ui:
  bundle:
    url: https://github.com/Field-Day-2022/field-day-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true

runtime:
  fetch: true

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
